### ISSUE TITLE
Use self-hosted CI runners

### ISSUE THREAD

**Issue by gpelouze** [NaaVRE/NaaVRE-containerizer-service#1]
Added `RUNNER_ACCESS_TOKEN` secret and `PREFERRED_ACTIONS_RUNNER` variable to repo

We need to change https://github.com/NaaVRE/NaaVRE-containerizer-service/blob/b88110e049ff8117a0c6451adc28e612be3c3339/.github/workflows/make.yml#L27 to

```yaml
      - id: choose-runner
        uses: QCDIS/choose-action-runner@v2
        with:
          preferred-runner: ${{ vars.PREFERRED_ACTIONS_RUNNER }}
          fallback-runner: ubuntu-latest
          github-token: ${{ secrets.RUNNER_ACCESS_TOKEN }}
```

(Doc: https://github.com/QCDIS/infrastructure/blob/main/doc/ci-runners.md#adding-runners-to-a-new-repository)
