### ISSUE TITLE
import numpy not detected in Python

### ISSUE THREAD

**Issue by skoulouzis** [NaaVRE/NaaVRE-containerizer-service#67]
If we have the code:
```python
import numpy
```
We do not see it in the environment.yaml:
```yaml
name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - papermill
  - ipykernel
```
